Trazendo a image gerada no codenarc-action
asaasdev/codenarc-docker pull request #19
Opened 2021-09-27 16:37 UTC by jemersonmaia

Transferindo criação da imagem que estava no projeto `codenarc-action` para o projeto `codenarc-docker`, pois isso vai permitir construir a imagem antes de ser utilizada no `codenarc-action`, melhorando a performance em sua utilização.

Com o objetivo de facilitar os testes, o workflow ci.yml fará publicação de uma imagem ao realizar pull request (com o número da PR) e ao criar uma release manual (podendo ser versão beta, snapshot, rc, etc).

Já o workflow release.yml, que utiliza [bumpr](https://github.com/haya14busa/action-bumpr) fará publicação da imagem latest e última versão gerado ao confirmar (merge) a PR.

O action.yml do projeto `codenarc-action` poderá passar a ter a configuração:

```
runs:
  using: 'docker'
  image: 'docker://docker.io/asaasdev/codenarc:latest' # ou a última versão fixa
```

2021-09-27 17:17 UTC, luiszimmermann requested changes

2021-09-27 17:17 UTC, luiszimmermann commented on .github/dependabot.yml
> -  - package-ecosystem: "github-actions" # See documentation for possible values
Tem algum motivo pra remoção do `dependabot`?

2021-09-27 17:17 UTC, luiszimmermann commented on .github/workflows/ci.yml
> +        uses: docker/build-push-action@v2.6.1
Voltou a versão para a `2.6.1`

2021-09-27 17:17 UTC, luiszimmermann commented on .github/workflows/ci.yml
> -        name: Set up QEMU
Essa parte do `QEMU` e do `buildx` é importante pois ele constrói uma imagem agnóstica que pode rodar em runtimes que não sejam o docker com total compatibilidade. É a maneira mais nova e correta de construir imagens.

2021-09-27 17:17 UTC, luiszimmermann commented on .github/workflows/release.yml
> +            jfnandopr/codenarc:${{ steps.get-latest-tag.outputs.tag }}
Precisa ajustar para o repositório do `asaasdev`

2021-09-27 17:17 UTC, luiszimmermann commented on .github/workflows/release.yml
> +      - name: Build and push
Aqui é necessário colocar aquele esquema do `QEMU` e `buildx`

2021-09-27 17:41 UTC, jemersonmaia commented on .github/workflows/ci.yml
> +        uses: docker/build-push-action@v2.6.1
Corrigido

2021-09-27 17:41 UTC, jemersonmaia commented on .github/workflows/ci.yml
> -        name: Set up QEMU
Entendi. Voltei essa configuração.

2021-09-27 17:42 UTC, jemersonmaia commented on .github/workflows/release.yml
> +            jfnandopr/codenarc:${{ steps.get-latest-tag.outputs.tag }}
Corrigido

2021-09-27 17:42 UTC, jemersonmaia commented on .github/workflows/release.yml
> +      - name: Build and push
Adicionado.

2021-09-27 17:44 UTC, jemersonmaia commented on .github/dependabot.yml
> -  - package-ecosystem: "github-actions" # See documentation for possible values
Aqui eu removi essa parte:

```
- package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
``` 

Ela não é usada só quando o projeto é do tipo `github-actions`?

2021-09-27 17:51 UTC, luiszimmermann commented on .github/dependabot.yml
> -  - package-ecosystem: "github-actions" # See documentation for possible values
Entendi, mas não, ela é usada para verificar as versões das actions usadas no repositório.

2021-09-27 18:22 UTC, jemersonmaia commented on .github/dependabot.yml
> -  - package-ecosystem: "github-actions" # See documentation for possible values
Legal! Corrigido.

2021-09-28 12:40 UTC, luiszimmermann approved these changes
LGTM,
Mas eu tenho uma dúvida, a action do ci terá acesso aos secrets necessários em novos PRs para realizar o push no docker hub?

2021-09-28 13:59 UTC, jemersonmaia commented
> LGTM, Mas eu tenho uma dúvida, a action do ci terá acesso aos secrets necessários em novos PRs para realizar o push no docker hub? Se sim, seria possível um PR alterar o ci e sobreescrever a imagem `latest`?

O ci tem acesso ao secrets e dependendo da configuração alterada no ci.yml poderia sobrescrever sim. A configuração atual é sem `flavor`, onde [por padrão o latest é `auto`](https://github.com/docker/metadata-action#flavor-input):

```
- name: Docker meta
  id: meta
  uses: docker/metadata-action@v3
  with:          
    images: |
      asaasdev/codenarc
    tags: |
      type=ref,event=pr
      type=semver,pattern={{version}}
```

Caso seja alterado para o exemplo abaixo, sempre mandaria a latest, mesmo sem uma PR:

```
- name: Docker meta
  id: meta
  uses: docker/metadata-action@v3
  with:          
    images: |
      asaasdev/codenarc
    tags: |
      type=ref,event=pr
      type=semver,pattern={{version}}
    flavor: |
      latest=true
```

2021-09-28 14:15 UTC, jemersonmaia commented
> > LGTM, Mas eu tenho uma dúvida, a action do ci terá acesso aos secrets necessários em novos PRs para realizar o push no docker hub? Se sim, seria possível um PR alterar o ci e sobreescrever a imagem `latest`?
> 
> O ci tem acesso ao secrets e dependendo da configuração alterada no ci.yml poderia sobrescrever sim. A configuração atual é sem `flavor`, onde [por padrão o latest é `auto`](https://github.com/docker/metadata-action#flavor-input):
> 
> ```
> - name: Docker meta
>   id: meta
>   uses: docker/metadata-action@v3
>   with:          
>     images: |
>       asaasdev/codenarc
>     tags: |
>       type=ref,event=pr
>       type=semver,pattern={{version}}
> ```
> 
> Caso seja alterado para o exemplo abaixo, sempre mandaria a latest, mesmo sem uma PR:
> 
> ```
> - name: Docker meta
>   id: meta
>   uses: docker/metadata-action@v3
>   with:          
>     images: |
>       asaasdev/codenarc
>     tags: |
>       type=ref,event=pr
>       type=semver,pattern={{version}}
>     flavor: |
>       latest=true
> ```

Luis, vou precisar alterar a configuração 

```
tags: |
    type=ref,event=pr
    type=semver,pattern={{version}}
```

para 

```
tags: |
    type=ref,event=pr
    type=semver,pattern={{raw}}
```

Isso porque são dois actions diferentes que obtêm a versão da release (tags):

- [docker/metadata-action@v3 do ci.yml](https://github.com/docker/metadata-action)
- [actions-ecosystem/action-get-latest-tag@v1 no release.yml](https://github.com/marketplace/actions/actions-ecosystem-action-get-latest-tag)

Não foi possível usar o mesmo do ci no release pois o release usa bumpr pra gerar nova release de forma automática, o que não é pega no docker/metadata-action@v3. Porém, ambas tratam versão de formas diferentes. O action-get-latest-tag não remove o **v** da tag e não tem uma forma de configurar isso. Já no metadata-action é possível configurar com o `raw` onde ele passará a usar o **v** em suas versões também.

Só destacando que o metadata-action usará a tag pra gerar uma nova imagem somente se for criado uma release manualmente. Caso contrário só será utilizada somente no PR. Quem deve liberar a versão final e a latest é o release.yml após o bumpr criar a release de forma automática.

2021-10-04 13:08 UTC, luiszimmermann approved these changes

2021-10-04 13:49 UTC, merged